# Declare global variables for package check
globalVariables(
  c(
    # Data manipulation
    ".data",
    ".env",
    ":=",
    ".row_id",
    ".should_fallback",
    ".active_key",
    ".temp_key",

    # Geographic identifiers
    "adm0",
    "adm1",
    "adm2",
    "lat",
    "lon",
    "x",
    "y",
    "loc",
    "location",
    "country",

    # Cluster/survey identifiers
    "cluster_id",
    "stratum_id",
    "hhid",
    "survey_id",
    "survey_year",
    "survey_type",
    "survey_weight",
    "DHSYEAR",

    # Time variables
    "year",
    "month",
    "month_num",
    "yearmon",
    "date",
    "date_raw",
    "interview_cmc",
    "interview_date",
    "median_date",
    "birth_cmc",

    # Demographics
    "age",
    "age_months",
    "sex",
    "mother",
    "hh_size",
    "hh_members",
    "is_under5",
    "is_pregnant",
    "is_pregnant_woman",
    "child_alive",
    "birth_age",
    "birth_index",
    "months_since_birth",

    # PfPR variables (microscopy)
    "mic_pos",
    "mic_res",
    "tested_mic",
    "n_tested_mic",
    "n_pos_mic",
    "pfpr_mic",
    "pfpr_mic_low",
    "pfpr_mic_upp",
    "pfpr_mic_se",

    # PfPR variables (RDT)
    "rdt_pos",
    "rdt_res",
    "tested_rdt",
    "n_tested_rdt",
    "n_pos_rdt",
    "pfpr_rdt",
    "pfpr_rdt_low",
    "pfpr_rdt_upp",
    "pfpr_rdt_se",

    # General testing
    "n_pos",
    "n_tested",
    "raw_prop",
    "n_clusters",
    "present",

    # Under-5 mortality
    "n_births",
    "n_deaths",
    "u5mr",
    "u5mr_low",
    "u5mr_upp",
    "u5mr_raw",
    "death_age_months",
    "died_in_interval",
    "died_under5",
    "deaths",
    "exposed",
    "q",
    "q_under1",
    "q_age1",
    "q_age2",
    "q_age3",
    "q_age4",
    "deaths_under1",
    "deaths_age1",
    "deaths_age2",
    "deaths_age3",
    "deaths_age4",
    "exposed_under1",
    "total_deaths",

    # ITN variables
    "hh_has_itn",
    "hh_sufficient_nets",
    "num_itns",
    "n_itns",
    "has_itn",
    "itn_access",
    "itn_access_ratio",
    "access_ratio",
    "has_access",
    "n_with_access",
    "itn_used",
    "itn_used_preg",
    "itn_used_u5",
    "potential_users",
    "person_index",
    "n_individuals",
    "ci_l.itn_used_preg",
    "ci_l.itn_used_u5",
    "ci_u.itn_used_preg",
    "ci_u.itn_used_u5",

    # IRS variables
    "sprayed",
    "irs_sprayed",
    "dhs_irs",
    "dhs_irs_low",
    "dhs_irs_upp",
    "dhs_n_households_irs",
    "dhs_n_sprayed",
    "ci_l.sprayed",
    "ci_u.sprayed",

    # Care-seeking behavior (WMR methodology)
    "had_fever",
    "fever",
    "care_category",
    "has_public",
    "has_chw",
    "has_private_formal",
    "has_private_informal",
    "has_pharmacy",
    "csb_public",
    "csb_private",
    "csb_private_formal_pha",
    "csb_any_treatment",
    "csb_no_treatment",
    "csb_trained_provider",
    "csb_any",
    "csb_none",
    "csb_trained",
    "csb",
    "visited",
    "is_public",
    "is_private",
    "is_none",
    "sought_any",
    "sought_none",
    "sought_private",
    "sought_public",
    "n_fever",
    "n_sought_any",
    "n_sought_none",
    "n_sought_private",
    "n_sought_public",
    "n_public",
    "n_private",
    "n_none",
    "n_trained",
    "csb_none_low",
    "csb_none_upp",
    "csb_trained_low",
    "csb_trained_upp",
    "ci_l.csb_public",
    "ci_u.csb_public",
    "ci_l.csb_private",
    "ci_u.csb_private",
    "ci_l.csb_no_treatment",
    "ci_u.csb_no_treatment",
    "ci_l.csb_trained_provider",
    "ci_u.csb_trained_provider",
    "ci_l.is_public",
    "ci_u.is_public",
    "ci_l.is_private",
    "ci_u.is_private",
    "ci_l.is_none",
    "ci_u.is_none",

    # Fever prevalence (cascade step 0)
    "fever_raw",
    "dhs_fever",
    "dhs_fever_low",
    "dhs_fever_upp",
    "dhs_n_children",
    "ci_l.had_fever",
    "ci_u.had_fever",

    # Malaria diagnostic testing (cascade step 2)
    "blood_taken",
    "had_test",
    "dhs_malaria_dx",
    "dhs_malaria_dx_low",
    "dhs_malaria_dx_upp",
    "dhs_n_febrile",
    "dhs_n_tested_dx",
    "ci_l.had_test",
    "ci_u.had_test",

    # Antimalarial treatment (cascade step 3)
    "received_antimalarial",
    "has_antimalarial",
    "dhs_antimalarial",
    "dhs_antimalarial_low",
    "dhs_antimalarial_upp",
    "dhs_n_antimalarial",
    "ci_l.has_antimalarial",
    "ci_u.has_antimalarial",

    # MBG binary indicators (fever, malaria_dx, antimalarial)
    "fever_binary",
    "dx_binary",
    "am_binary",

    # ACT treatment (cascade step 4)
    "has_act",
    "has_rdt_pos",
    "rdt_result",
    "received_act",
    "test_positive",
    "has_act_tested",
    "got_act",
    "act_binary",
    "ci_l.has_act",
    "ci_u.has_act",
    "ci_l.got_act",
    "ci_u.got_act",
    "ci_l.has_rdt_pos",
    "ci_u.has_rdt_pos",
    "dhs_act",
    "dhs_act_low",
    "dhs_act_upp",
    "dhs_act_tested",
    "dhs_act_tested_low",
    "dhs_act_tested_upp",
    "dhs_febrile_rdt_pos",
    "dhs_febrile_rdt_pos_low",
    "dhs_febrile_rdt_pos_upp",
    "dhs_febrile_rdt_pos_act",
    "dhs_febrile_rdt_pos_act_low",
    "dhs_febrile_rdt_pos_act_upp",
    "dhs_n_act",
    "dhs_n_fever",
    "dhs_n_tested",

    # Case management cascade
    "estimate",
    "low",
    "upp",
    "n_eligible",
    "n_positive",

    # IPTp indicators
    "iptp_1plus",
    "iptp_2plus",
    "iptp_3plus",
    "iptp_4plus",
    "sp_taken",
    "sp_doses",
    "iptp_1",
    "iptp_1_low",
    "iptp_1_upp",
    "iptp_2",
    "iptp_2_low",
    "iptp_2_upp",
    "iptp_3",
    "iptp_3_low",
    "iptp_3_upp",
    "iptp_4",
    "iptp_4_low",
    "iptp_4_upp",
    "n_women",
    "n_recent_births",
    "n_iptp_1plus",
    "n_iptp_2plus",
    "n_iptp_3plus",
    "n_iptp_4plus",
    "has_1plus",
    "has_2plus",
    "has_3plus",
    "has_4plus",
    "has_1only",
    "has_2only",
    "has_3only",

    # Anemia indicators
    "hemoglobin",
    "hb_raw",
    "tested_hb",
    "n_tested_hb",
    "severe_anemia",
    "n_severe_anemia",
    "severe_anemia_low",
    "severe_anemia_upp",
    "severe_anemia_se",
    "has_any_anemia",
    "has_moderate_plus",
    "has_severe",
    "has_mild_only",
    "has_moderate_only",
    "has_severe_only",

    # ANC indicators
    "anc_visits",
    "has_anc1",
    "has_anc3",
    "has_anc4",
    "has_anc8",
    "dhs_anc_1plus",
    "dhs_anc_1plus_low",
    "dhs_anc_1plus_upp",
    "dhs_anc_3plus",
    "dhs_anc_3plus_low",
    "dhs_anc_3plus_upp",
    "dhs_anc_4plus",
    "dhs_anc_4plus_low",
    "dhs_anc_4plus_upp",
    "dhs_anc_8plus",
    "dhs_anc_8plus_low",
    "dhs_anc_8plus_upp",
    "dhs_n_recent_births",
    "ci_l.has_anc1",
    "ci_u.has_anc1",
    "ci_l.has_anc3",
    "ci_u.has_anc3",
    "ci_l.has_anc4",
    "ci_u.has_anc4",
    "ci_l.has_anc8",
    "ci_u.has_anc8",

    # Vaccination/EPI indicators
    "vaccinated",
    "fully_vaccinated",
    "has_bcg",
    "has_dpt3",
    "has_polio3",
    "has_measles1",
    "dhs_epi_bcg",
    "dhs_epi_bcg_low",
    "dhs_epi_bcg_upp",
    "dhs_epi_dpt1",
    "dhs_epi_dpt1_low",
    "dhs_epi_dpt1_upp",
    "dhs_epi_dpt2",
    "dhs_epi_dpt2_low",
    "dhs_epi_dpt2_upp",
    "dhs_epi_dpt3",
    "dhs_epi_dpt3_low",
    "dhs_epi_dpt3_upp",
    "dhs_epi_polio1",
    "dhs_epi_polio1_low",
    "dhs_epi_polio1_upp",
    "dhs_epi_polio2",
    "dhs_epi_polio2_low",
    "dhs_epi_polio2_upp",
    "dhs_epi_polio3",
    "dhs_epi_polio3_low",
    "dhs_epi_polio3_upp",
    "dhs_epi_measles1",
    "dhs_epi_measles1_low",
    "dhs_epi_measles1_upp",
    "dhs_epi_measles2",
    "dhs_epi_measles2_low",
    "dhs_epi_measles2_upp",
    "dhs_epi_fully_vaccinated",
    "dhs_epi_fully_vaccinated_low",
    "dhs_epi_fully_vaccinated_upp",
    "dhs_n_epi_eligible",

    # SMC indicators
    "smc_receipt",
    "received_smc",
    "dhs_smc",
    "dhs_smc_low",
    "dhs_smc_upp",
    "dhs_n_smc_eligible",
    "dhs_n_smc_received",
    "ci_l.received_smc",
    "ci_u.received_smc",

    # Wealth/inequality
    "wealth_quintile",
    "wealth_score",
    "weight",
    "dominant_quintile",
    "gini",
    "gini_sample_size",
    "n_households",
    "weighted_households",
    "prop_middle",
    "prop_poorer",
    "prop_poorest",
    "prop_richer",
    "prop_richest",
    "cum_pop",
    "cum_wealth",
    "group",
    "group_pop",
    "group_wealth",

    # DHS household variables (h32 series)
    "h32a", "h32b", "h32c", "h32d", "h32e", "h32f", "h32g", "h32h",
    "h32i", "h32j", "h32k", "h32l", "h32m", "h32n", "h32o", "h32p",
    "h32q", "h32r", "h32s", "h32t", "h32u", "h32v", "h32w", "h32x", "h32y",
    "hc1",
    "v001", "v002", "v003",

    # Join variables
    "join_status",
    "kr_cluster_join",
    "kr_hh_join",
    "kr_line_join",
    "pr_cluster_join",
    "pr_hh_join",
    "pr_line_join",
    "hv001",
    "hv002",
    "hvidx",

    # Health facility/HMIS variables
    "hf_uid",
    "conf",
    "pres",
    "test",
    "test_bin",
    "total_conf",
    "tpr",
    "tpr_raw",
    "tpr_clean",
    "tpr_actual",
    "tpr_source",
    "tpr_adm0",
    "tpr_adm1",
    "tpr_adm2",
    "tpr_prev_year",
    "tpr_rolling",
    "pres_clean",

    # Facility counts and aggregations
    "n_facilities_adm2",
    "n_facilities_adm1",
    "n_facilities_adm0",
    "n_fac_adm2",
    "n_fac_adm1",
    "n_fac_adm0",
    "sum_conf_adm2",
    "sum_conf_adm1",
    "sum_conf_adm0",
    "sum_test_adm2",
    "sum_test_adm1",
    "sum_test_adm0",
    "sum_c_adm2",
    "sum_c_adm1",
    "sum_c_adm0",
    "sum_t_adm2",
    "sum_t_adm1",
    "sum_t_adm0",
    "n_active_facilities",
    "n_total_facilities",
    "activity_status",

    # Proxy and fallback variables
    "proxy_adm2",
    "proxy_adm1",
    "proxy_adm0",
    "proxy_prev_year",
    "proxy_prev_year_same",
    "proxy_prev_year_prev_month",
    "proxy_adjacent_month",
    "proxy_roll3",
    "proxy_level",
    "proxy_value",
    "error_adm2",
    "error_adm1",
    "error_adm0",
    "error_prev_year",
    "error",

    # Rolling/temporal variables
    "month_offset",
    "prev_year",
    "prev_month",
    "prev_conf",
    "prev_test",
    "rolling_month",
    "rolling_year",
    "rolling_conf",
    "rolling_test",
    "rolling_month_join",
    "n_months_used",

    # QC flags
    "flag_conf_gt_test",
    "flag_inactive",
    "flag_tpr_extreme",
    "flag_tpr_missing",
    "flag_tpr_proxy",
    "flag_tpr_valid",
    "flag_low_test",
    "flag_missing_conf",
    "flag_zero_test",
    "flag_pop_zero",
    "flag_pop_missing",
    "flag_reprate_missing",
    "flag_reprate_low",
    "flag_cs_missing",
    "flag_n1_invalid",
    "flag_n2_invalid",
    "flag_n3_invalid",
    "flag_n4_invalid",
    "flag_n5_invalid",

    # Reporting rate
    "reporting_rate",
    "reprate",
    "reprate_clean",
    "repr_bin",

    # Incidence cascade
    "pop",
    "n",
    "n0",
    "n1",
    "n2",
    "n3",
    "n0_cases",
    "n1_cases",
    "n1_cases_fac",
    "n2_cases",
    "n3_cases",
    "n4_cases",
    "n5_cases",
    "n0_incidence",
    "n1_incidence",
    "n2_incidence",
    "n3_incidence",
    "n4_incidence",
    "n5_incidence",
    "incidence_level",
    "incidence",
    "cs_public",
    "cs_private",
    "cs_none",
    "cs_public_clean",
    "cs_private_clean",
    "cs_none_clean",
    "cs_bin",
    "f_priv_eff",
    "adj_private",
    "adj_none",
    "adj_none_reduced",
    "adj_priv",
    "total",
    "n2_annual",
    "n3_annual",
    "n2_share",

    # Statistics/metrics
    "ci_l",
    "ci_u",
    "ci_low",
    "ci_high",
    "sd",
    "se",
    "Class",
    "LCI",
    "UCI",
    "R",
    "nfac_bin",
    "mae",
    "mae_n2",
    "mae_n3",
    "bias",
    "agreement_05",
    "agreement_10",
    "rmse",
    "correlation",
    "err_n2",
    "err_n3",
    "step",

    # MBG variables
    ".",
    "indicator",
    "samplesize",
    "positive",
    "variable",
    "value",
    "level",
    "n_distinct",
    "n_positive_either",
    "n_positive_rdt",
    "n_positive_mic",
    "prop_raw_either",
    "prop_raw_rdt",
    "prop_raw_mic",

    # DHS survey output columns (prefixed for sntutils compatibility)
    "dhs_csb_any",
    "dhs_csb_none",
    "dhs_csb_none_low",
    "dhs_csb_none_upp",
    "dhs_csb_private",
    "dhs_csb_public",
    "dhs_csb_trained",
    "dhs_dominant_quintile",
    "dhs_gini",
    "dhs_gini_sample_size",
    "dhs_n_births",
    "dhs_n_deaths",
    "dhs_n_fever",
    "dhs_n_households",
    "dhs_n_none",
    "dhs_n_pos_mic",
    "dhs_n_pos_rdt",
    "dhs_n_private",
    "dhs_n_public",
    "dhs_n_severe_anemia",
    "dhs_n_tested_hb",
    "dhs_n_tested_mic",
    "dhs_n_tested_rdt",
    "dhs_n_trained",
    "dhs_pfpr_mic",
    "dhs_pfpr_mic_low",
    "dhs_pfpr_mic_se",
    "dhs_pfpr_mic_upp",
    "dhs_pfpr_rdt",
    "dhs_pfpr_rdt_low",
    "dhs_pfpr_rdt_se",
    "dhs_pfpr_rdt_upp",
    "dhs_prop_middle",
    "dhs_prop_poorer",
    "dhs_prop_poorest",
    "dhs_prop_richer",
    "dhs_prop_richest",
    "dhs_severe_anemia",
    "dhs_severe_anemia_low",
    "dhs_severe_anemia_se",
    "dhs_severe_anemia_upp",
    "dhs_u5mr",
    "dhs_u5mr_low",
    "dhs_u5mr_upp",
    "dhs_weighted_households",

    # File handling
    "file_path",
    "file_type",
    "file_types",
    "parts"
  )
)
